# Generated by Django 6.0.1 on 2026-05-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tiene_suscripcion_activa',
            field=models.BooleanField(default=False),
        ),
    ]
