# Generated by Django 6.0.1 on 2026-03-30 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcripciones', '0001_initial'),
        ('usuarios', '0002_remove_arquitecto_clientes_remove_arquitecto_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='usuarios.cliente', verbose_name='Cliente'),
        ),
    ]
