# Generated by Django 6.0.1 on 2026-03-30 13:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_remove_arquitecto_clientes_remove_arquitecto_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id_suscripcion', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Suscripción')),
                ('tipo_suscripcion', models.CharField(choices=[('Basico', 'Básico'), ('Premium', 'Premium'), ('Estandar', 'Estándar')], default='Basico', max_length=50, verbose_name='Tipo de Suscripción')),
                ('precio', models.DecimalField(decimal_places=2, default=9.99, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Precio')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='usuarios.cliente', verbose_name='Cliente')),
            ],
        ),
    ]
