# Generated by Django 6.0.1 on 2026-04-03 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0002_alter_suscripcion_cliente'),
        ('usuarios', '0004_remove_arquitecto_cuenta_bancaria_arquitecto_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente', verbose_name='Cliente'),
        ),
    ]
