# Generated by Django 6.0.1 on 2026-03-30 13:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_remove_arquitecto_clientes_remove_arquitecto_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id_plano', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Plano')),
                ('tamano', models.DecimalField(decimal_places=2, default=0.01, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Tamaño (m²)')),
                ('formato', models.CharField(choices=[('PDF', 'PDF'), ('DWG', 'DWG')], default='PDF', max_length=50, verbose_name='Formato')),
                ('archivo', models.FileField(null=True, upload_to='planos_archivos/', verbose_name='Archivo del Plano')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('fecha_entrega', models.DateField(default='2024-01-01', verbose_name='Fecha de Entrega')),
                ('arquitecto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='usuarios.arquitecto', verbose_name='Arquitecto Diseñador')),
            ],
        ),
    ]
