# Generated by Django 6.0.1 on 2026-03-30 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquitecto',
            name='clientes',
        ),
        migrations.RemoveField(
            model_name='arquitecto',
            name='id',
        ),
        migrations.RemoveField(
            model_name='arquitecto',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='user',
        ),
        migrations.AddField(
            model_name='arquitecto',
            name='apellidos',
            field=models.CharField(default='Sin apellidos', max_length=150),
        ),
        migrations.AddField(
            model_name='arquitecto',
            name='correo_electronico',
            field=models.EmailField(default='temporal@correo.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='arquitecto',
            name='cuenta_bancaria',
            field=models.CharField(default='ES0000000000000000000000', max_length=50),
        ),
        migrations.AddField(
            model_name='arquitecto',
            name='nif_arquitecto',
            field=models.CharField(default='00000000T', max_length=20, primary_key=True, serialize=False, verbose_name='DNI'),
        ),
        migrations.AddField(
            model_name='arquitecto',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=100),
        ),
        migrations.AddField(
            model_name='arquitecto',
            name='telefono',
            field=models.CharField(default='000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='arquitecto',
            field=models.ForeignKey(default='12345678X', on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='usuarios.arquitecto', verbose_name='Arquitecto Diseñador'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='correo_electronico',
            field=models.EmailField(default='cliente@correo.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cuenta_bancaria',
            field=models.CharField(default='ES0000000000000000000000', max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nif_cliente',
            field=models.CharField(default='00000000X', max_length=20, primary_key=True, serialize=False, verbose_name='NIF'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nom_empresa',
            field=models.CharField(default='Empresa S.A.', max_length=200, verbose_name='Nombre de la Empresa'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(default='000000000', max_length=20),
        ),
    ]
