# Generated by Django 6.0.1 on 2026-03-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_arquitecto_clientes_remove_arquitecto_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquitecto',
            name='nif_arquitecto',
            field=models.CharField(default='00000000T', max_length=20, primary_key=True, serialize=False, verbose_name='NIF'),
        ),
    ]
