# Generated by Django 6.0.1 on 2026-03-30 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_arquitecto_nif_arquitecto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquitecto',
            name='cuenta_bancaria',
        ),
        migrations.AddField(
            model_name='arquitecto',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_arquitecto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='arquitecto',
            name='apellidos',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='arquitecto',
            name='correo_electronico',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='arquitecto',
            name='nif_arquitecto',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='NIF'),
        ),
        migrations.AlterField(
            model_name='arquitecto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='arquitecto',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='arquitecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='usuarios.arquitecto', verbose_name='Arquitecto Diseñador'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo_electronico',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cuenta_bancaria',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nif_cliente',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='NIF'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nom_empresa',
            field=models.CharField(max_length=200, verbose_name='Nombre de la Empresa'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
