# Generated by Django 6.0.1 on 2026-05-27 08:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id_plano', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Plano')),
                ('titulo', models.CharField(help_text='Ej: Plano Eléctrico Cocina o Distribución Planta Baja', max_length=150, verbose_name='Título / Descripción del Plano')),
                ('tamano', models.DecimalField(decimal_places=2, default=0.01, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Tamaño (m²)')),
                ('formato', models.CharField(choices=[('PDF', 'PDF'), ('DWG', 'DWG')], default='PDF', max_length=50, verbose_name='Formato')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='planos_clientes/', verbose_name='Archivo Base del Cliente')),
                ('archivo_procesado', models.FileField(blank=True, null=True, upload_to='planos_procesados/', verbose_name='Archivo Procesado (Arquitecto)')),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En Proceso'), ('LISTO', 'Listo para Descarga')], default='EN_PROCESO', max_length=20, verbose_name='Estado del Trabajo')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('fecha_entrega', models.DateField(default='2026-01-01', verbose_name='Fecha de Entrega')),
                ('arquitecto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='planos_asignados', to='usuarios.arquitecto', verbose_name='Arquitecto Diseñador')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_solicitados', to='usuarios.cliente', verbose_name='Cliente Solicitante')),
            ],
        ),
    ]
